version: "3.7"

services:
  postgres:
    container_name: gym_postgres
    image: postgres:11
    ports:
      - 5432:5432
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    environment: 
      - POSTGRES_DB=gympointDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=gympoint
  
  mongo:
    container_name: gym_mongo
    image: mongo
    ports: 
      - 27017:27017
  
  redis:
    container_name: gym_redis
    image: redis:alpine
    ports: 
      - 6379:6379
    volumes:
      - "./data/redis:/var/lib/redis/data"